on:
  push:
    paths:
      - 'back/**'

name: CI - Back
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    env:
      working-directory: ./back
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Run composer install
        run: composer install --prefer-dist --dev
      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer fix src/ --dry-run --diff --config .php_cs
      - name: Run php-md
        run: vendor/bin/phpmd src/ text phpmd.xml --exclude 'tests/,var/,vendor/' --suffixes php || true
      - name: Run php-cpd
        run: vendor/bin/phpcpd src/
      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer fix src/ --dry-run --diff --config .php_cs
      - name: Run php-md
        run: vendor/bin/phpmd src/ text phpmd.xml --exclude 'tests/,var/,vendor/' --suffixes php || true
      - name: Run php-cpd
        run: vendor/bin/phpcpd src/

