on:
  push:
    paths:
      - 'front/**'

name: CI - Front
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    env:
      working-directory: ./front
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 8
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Run npm install
        run: npm install
      - name: Run lint js
        run: npm run lint:js
      - name: Run lint scss
        run: npm run lint:scss
      - name: Run test
        run: npm test -- --ci

